conditions: v0

language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
  - 10

before_install: npm i minimatch && node travis-ignore.js

install: npm run travis-install

script: npm run travis-script

after_script: npm run travis-coverage
