language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "node"
  - 10

install: npm i && cd test && npm i && cd ..

script: npm run travis

after_script: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
